deeplay-io/nice-grpc

- packages/nice-grpc/README.md
- packages/nice-grpc/fixtures/test.proto
- packages/nice-grpc/jest.config.js
- packages/nice-grpc/package.json
- packages/nice-grpc/src/__tests__/bidiStreaming.ts
- packages/nice-grpc/src/__tests__/clientMiddleware/bidiStreaming.ts
- packages/nice-grpc/src/__tests__/clientMiddleware/chain.ts
- packages/nice-grpc/src/__tests__/clientMiddleware/clientStreaming.ts
- packages/nice-grpc/src/__tests__/clientMiddleware/serverStreaming.ts
- packages/nice-grpc/src/__tests__/clientMiddleware/unary.ts
- packages/nice-grpc/src/__tests__/clientStreaming.ts
- packages/nice-grpc/src/__tests__/defaultCallOptions.ts
- packages/nice-grpc/src/__tests__/serverClass.ts
- packages/nice-grpc/src/__tests__/serverMiddleware/bidiStreaming.ts
- packages/nice-grpc/src/__tests__/serverMiddleware/chain.ts
- packages/nice-grpc/src/__tests__/serverMiddleware/clientStreaming.ts
- packages/nice-grpc/src/__tests__/serverMiddleware/perService.ts
- packages/nice-grpc/src/__tests__/serverMiddleware/serverStreaming.ts
- packages/nice-grpc/src/__tests__/serverMiddleware/unary.ts
- packages/nice-grpc/src/__tests__/serverStreaming.ts
- packages/nice-grpc/src/__tests__/ts-proto.ts
- packages/nice-grpc/src/__tests__/unary.ts
- packages/nice-grpc/src/service-definitions/index.ts
- packages/nice-grpc/src/service-definitions/ts-proto.ts
- yarn.lock
You can now use `ts-proto` with `outputServices=generic-definitions`.
- Requests on the client and responses on the server are automatically wrapped with `fromPartial`.
- Method options like `idempotency_level` are preserved and are visible in middleware.
> feat(nice-grpc): support `ts-proto` service definitions

- packages/nice-grpc-common/src/client/ClientError.ts
- packages/nice-grpc-common/src/server/ServerError.ts
`Error.captureStackTrace` is not available in Firefox, leading to the following error:
```
TypeError: Error.captureStackTrace is not a function
```
Similar issues can be found in other projects (https://github.com/trentm/node-bunyan/issues/224).
I'm only capturing the stack if the function is available. Let me know if that behavior suits you.
The stack trace still looks good without.
And no need to change in `*.test.ts` as the function is always available in node env.
> fix: check availability of Error.captureStackTrace before using it

- packages/nice-grpc-client-middleware-retry/package.json
- packages/nice-grpc-server-health/package.json
- packages/nice-grpc-server-middleware-terminator/package.json
- packages/nice-grpc-web/README.md
- packages/nice-grpc-web/package.json
- packages/nice-grpc/README.md
- packages/nice-grpc/package.json
- yarn.lock
Updated `ts-proto` compilations to use `ts-proto@1.97.0` with an option `useExactTypes=false`.
Closes #26
> chore: fix compatibility with `ts-proto`

- packages/nice-grpc-common/package.json
- packages/nice-grpc-common/src/client/ClientError.ts
- packages/nice-grpc-common/src/server/ServerError.ts
- yarn.lock
Use [ts-error](https://www.npmjs.com/package/ts-error) for custom errors.
> fix(nice-grpc-common): fix issues with `ServerError` and `ClientError` when transpiling to older environments

- packages/nice-grpc-client-middleware-retry/package.json
- packages/nice-grpc-error-details/package.json
- packages/nice-grpc-server-health/package.json
- packages/nice-grpc-server-middleware-terminator/package.json
- packages/nice-grpc-web/README.md
- packages/nice-grpc-web/package.json
- packages/nice-grpc-web/src/__tests__/ts-proto.ts
- packages/nice-grpc/README.md
- packages/nice-grpc/package.json
- packages/nice-grpc/src/__tests__/ts-proto.ts
- yarn.lock
Starting from version `1.112.0` [`ts-proto`](https://github.com/stephenh/ts-proto) is able to generate TypeScript interfaces for `nice-grpc` service implementations and clients. So instead of `ServiceImplementation<typeof YourServiceDefinition>` you can write `YourServiceImplementation` and instead of `Client<typeof YourServiceDefinition>` just use `YourServiceClient`. This will also make IDE hints more developer-friendly.
To start using this feature, add `outputServices=nice-grpc` to `ts_proto_opt`. Note that `outputServices=nice-grpc` is still required, i.e. you should include `outputServices` option twice. For complete examples see the docs on compiling Protobuf files for [`nice-grpc`](https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc/README.md#using-ts-proto) and …
> feat: add support for `ts-proto` server and client interfaces

- packages/nice-grpc/src/__tests__/channel.ts
- packages/nice-grpc/src/client/channel.ts
Instead, pass these unknown addresses directly through to the Channel constructor
Closes #167
_I'm sorry in advance if tests don't pass on the first try. I have an M1 and this project doesn't want to build no matter how hard I try_
> fix(channel): no longer reject invalid protocols

- packages/nice-grpc/src/__tests__/channel.ts
- packages/nice-grpc/src/client/channel.ts
If a client is set up using **secure credentials** with only the hostname **and no protocol**, the current logic defaults to the insecure 80 port.
This refactors the `createChannel` logic and then adds some logic to consider the possibility that the credentials passed in are already set up to be secure.
Since [ChannelCredentials is an abstract class](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel-credentials.ts#L66) - we should always expect to be passed an implemented credential object that has _isSecure() set to either [true](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel-credentials.ts#L220) or [false](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel-credentials.ts#L184) (or nothing at all, which then …
> feat(nice-grpc): include support for implicit secure protocol

- packages/nice-grpc/src/service-definitions/grpc-js.ts
Prior to this fix the library incorrectly detected `grpc-js` service definitions generated by `ts-proto` as `ts-proto` generic definitions.
Closes #291
> fix(nice-grpc): fix runtime detection of grpc-js service definitions

- packages/nice-grpc-client-middleware-retry/README.md
- packages/nice-grpc-client-middleware-retry/src/index.ts
This status code may be returned from rate limiters and is unsafe to retry by default.
> feat!(nice-grpc-client-middleware-retry): don't retry `RESOURCE_EXHAUSTED`

- packages/nice-grpc-client-middleware-retry/src/index.ts
Server may return `CANCELLED` status on shutdown.
> feat(nice-grpc-client-middleware-retry): add `CANCELLED` to retryable codes

- packages/nice-grpc-web/src/service-definitions/ts-proto.ts
- packages/nice-grpc/src/service-definitions/ts-proto.ts
Updated ts-proto method definition to reflect this change: https://github.com/stephenh/ts-proto/pull/801
> fix(nice-grpc): ts-proto method definition

- packages/nice-grpc-web/src/__tests__/serverStreaming.ts
- packages/nice-grpc-web/src/client/decodeResponse.ts
Before this fix, empty emissions from server streams were delayed until next emission.
> fix(nice-grpc-web): fix delayed empty emissions in server stream

- packages/nice-grpc-web/src/__tests__/unary.ts
- packages/nice-grpc-web/src/client/makeCall.ts
- packages/nice-grpc-web/src/client/parseTrailer.ts
- gRPC status and message received in trailers-only response (the headers) get precedence over ones mapped from HTTP status codes.
- Actual trailer is tolerated in trailers-only response only if it's empty.
- `grpc-message` header value is decoded using URL encoding.
Closes #345
> fix(nice-grpc-web): correctly handle trailers-only responses

- packages/nice-grpc-web/src/client/transports/fetch.ts
Resolve https://github.com/deeplay-io/nice-grpc/issues/349 by adding an optional cache param for FetchTransport which allows developers to specify the cache strategy on fetch requests for nice-grpc-web
> add cache field to FetchTransportConfig

- packages/nice-grpc-error-details/src/ErrorDetails.ts
- packages/nice-grpc-error-details/src/index.test.ts
This PR is to support `BadRequest_FieldViolation/PreconditionFailure_Violation/QuotaFailure_Violation` errors to the rich client error instance. As per current behaviour, detail are mapped to `Any` type since these violations type of errors are currently not supported in the library.
I have a server in Golang side which can throw violation errors too in the error response. Hence this library should also support the ability to map the violation errors correctly to RichClientError instance
Resolution to the issue mentioned in this [thread](https://github.com/deeplay-io/nice-grpc/issues/369)
Closes #369
> feat(nice-grpc-error-details): include support for violation type of errors in rich client error detail instance

- packages/nice-grpc-web/src/client/makeInternalErrorMessage.ts
- packages/nice-grpc-web/test-server/traefik.ts
> fix(nice-grpc-web): don't put stack traces to internal and transport error messages

- packages/nice-grpc-prometheus/README.md
- packages/nice-grpc-prometheus/src/__tests__/customMetrics.ts
- packages/nice-grpc-prometheus/src/client.ts
- packages/nice-grpc-prometheus/src/common.ts
- packages/nice-grpc-prometheus/src/index.ts
- packages/nice-grpc-prometheus/src/server.ts
Hi!
I've found that the default buckets for histograms are not always suitable, and it would be useful to be able to customize them.
In looking for a way to change this I came to the conclusion that the most versatile and flexible way is to allow all metrics to be overridden.
> feat(nice-grpc-prometheus): add metrics customization

- packages/nice-grpc/README.md
relates to #424
I totally missed how `CallOptions` can be added to a client type when trying to create my own middleware. It's pretty obvious in hindsight but I thought this example might help others from missing this in the future.
> Add example to docs for extending a client Type with CallOptions

- packages/nice-grpc-error-details/package.json
The `nice-grpc-error-details` pacakge requires `long` to work: https://www.runpkg.com/?nice-grpc-error-details@0.2.1/lib/proto/google/protobuf/duration.js#5
Add `long` to `peerDependencies`, so pnpm can install it into a correct folder.
> fix(nice-grpc-error-details): add long to dependencies

- packages/nice-grpc-client-middleware-deadline/src/index.test.ts
- packages/nice-grpc-client-middleware-deadline/src/index.ts
The deadline middleware replaces the original signal with a new one and attaches listeners for the `abort` event. This works for signals that are not aborted yet but if a signal is already aborted before starting the gRPC call the deadline middleware would still make the request because it did not receive the `abort` event.
This change skips the deadline middleware completely for calls with an aborted signal. The `nice-grpc` library will handle the aborted signal and abort the call correctly.
> Skip deadline when signal is already aborted

- .github/workflows/ci.yaml
- lerna.json
- package.json
- yarn.lock
Had to remove NodeJS 14 and 16 from CI because these versions have reached end of life and not supported in Lerna 8.
> chore(deps-dev): upgrade to lerna 8

- .github/workflows/ci.yaml
`lerna test` with [`--since`](https://lerna.js.org/docs/features/run-tasks#run-tasks-affected-by-a-pr) flag does not trigger tests when only `yarn.lock` has changed, without updating `package.json`. This makes tests unreliable for most Dependabot updates.
> chore(ci): disable --since for test runs

- packages/nice-grpc/src/server/Server.ts
To reproduce, run `yarn test serverClass` in packages/nice-grpc
```
yarn run v1.22.22
$ jest serverClass
(node:28544) DeprecationWarning: Calling start() is no longer necessary. It can be safely omitted.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS  src/__tests__/serverClass.ts
```
The DeprecationWarning is from https://github.com/grpc/grpc-node/blob/3c9436be8eb3788173796d4c90d2abe036d0f798/packages/grpc-js/src/server.ts#L1156-L1159
> avoid server.start() deprecation warning

- packages/nice-grpc-web/test-server/envoy-tls.yaml
- packages/nice-grpc-web/test-server/envoy.yaml
> test(nice-grpc-web): force envoy to use ipv4

- packages/nice-grpc-server-reflection/package.json
- packages/nice-grpc-server-reflection/proto/grpc/reflection/v1/reflection.proto
- packages/nice-grpc-server-reflection/src/index.test.ts
- packages/nice-grpc-server-reflection/src/index.ts
BREAKING CHANGE: server reflection is now exposed via `grpc.reflection.v1.ServerReflection` service instead of `grpc.reflection.v1alpha.ServerReflection`. Tools like grpcurl should handle this automatically.
> feat(nice-grpc-server-reflection): use v1 protobufs
